namespace KidsTraining.App.Application.Learning.Markup;

internal static partial class LearningMarkupPatcher
{
    private static string BuildPickKokugoScript()
    {
        return """
pickKokugo(p){const g=this.effectiveGrade(p),stage=this.topicStage(p,'kokugo');const L=[
  {g:1,k:'山',r:'やま',pre:'',post:' に のぼる',mean:'たかい ところ'},{g:1,k:'川',r:'かわ',pre:'',post:' で あそぶ',mean:'みずが ながれる ところ'},{g:1,k:'花',r:'はな',pre:'あかい ',post:' が さく',mean:'くさきに さく もの'},{g:1,k:'空',r:'そら',pre:'あおい ',post:' を みる',mean:'あたまの うえ'},{g:1,k:'学校',r:'がっこう',pre:'まいにち ',post:' へ いく',mean:'べんきょうする ところ'},{g:1,k:'先生',r:'せんせい',pre:'やさしい ',post:'',mean:'おしえて くれる ひと'},{g:1,k:'雨',r:'あめ',pre:'',post:' が ふる',mean:'そらから おちる みず'},{g:1,k:'水',r:'みず',pre:'',post:' を のむ',mean:'のむ もの'},{g:1,k:'木',r:'き',pre:'大きな ',post:'',mean:'えだや はが ある'},{g:1,k:'犬',r:'いぬ',pre:'',post:' と あるく',mean:'どうぶつ'},{g:1,k:'耳',r:'みみ',pre:'',post:' で きく',mean:'おとを きく ところ'},{g:1,k:'手',r:'て',pre:'',post:' を あげる',mean:'ものを もつ ところ'},{g:1,k:'足',r:'あし',pre:'',post:' で はしる',mean:'あるく ところ'},{g:1,k:'町',r:'まち',pre:'',post:' を あるく',mean:'いえや みせが ある'},{g:1,k:'森',r:'もり',pre:'',post:' に 木が ある',mean:'木が たくさん ある'},{g:1,k:'名まえ',r:'なまえ',pre:'',post:' を 書く',mean:'よびかた'},{g:1,k:'石',r:'いし',pre:'',post:' を ひろう',mean:'かたい つぶ'},{g:1,k:'貝',r:'かい',pre:'うみで ',post:' を ひろう',mean:'うみに いる いきものの から'},{g:1,k:'虫',r:'むし',pre:'',post:' を つかまえる',mean:'ちいさな いきもの'},{g:1,k:'竹',r:'たけ',pre:'',post:' が のびる',mean:'ふしの ある くさき'},{g:1,k:'糸',r:'いと',pre:'',post:' を むすぶ',mean:'ほそながい もの'},{g:1,k:'車',r:'くるま',pre:'',post:' に のる',mean:'タイヤで はしる もの'},{g:1,k:'音',r:'おと',pre:'',post:' が きこえる',mean:'みみに きこえる もの'},{g:1,k:'草',r:'くさ',pre:'',post:' が はえる',mean:'みどりの しょくぶつ'},{g:1,k:'目',r:'め',pre:'',post:' で みる',mean:'ものを みる ところ'},{g:1,k:'口',r:'くち',pre:'',post:' を あける',mean:'たべる ところ'},{g:1,k:'月',r:'つき',pre:'よるの ',post:' が きれい',mean:'よぞらに ひかる もの'},{g:1,k:'立つ',r:'たつ',pre:'せきを ',post:'',mean:'あしで まっすぐに なる'},{g:1,k:'見る',r:'みる',pre:'そとを ',post:'',mean:'目で たしかめる'},{g:1,k:'白い',r:'しろい',pre:'',post:' くも',mean:'ゆきの いろ'},{g:1,k:'大きい',r:'おおきい',pre:'',post:' こえ',mean:'ちいさくない'},
  {g:2,k:'春',r:'はる',pre:'',post:' に 花が さく',mean:'あたたかい きせつ'},{g:2,k:'夏',r:'なつ',pre:'',post:' は あつい',mean:'あつい きせつ'},{g:2,k:'秋',r:'あき',pre:'',post:' に 木のはが かわる',mean:'すずしい きせつ'},{g:2,k:'冬',r:'ふゆ',pre:'',post:' は さむい',mean:'さむい きせつ'},{g:2,k:'朝',r:'あさ',pre:'',post:' に おきる',mean:'一日の はじまり'},{g:2,k:'昼',r:'ひる',pre:'',post:' に ごはんを 食べる',mean:'日中'},{g:2,k:'夜',r:'よる',pre:'',post:' に ねる',mean:'くらい じかん'},{g:2,k:'魚',r:'さかな',pre:'',post:' が およぐ',mean:'みずの 中の いきもの'},{g:2,k:'鳥',r:'とり',pre:'',post:' が とぶ',mean:'はねの ある いきもの'},{g:2,k:'馬',r:'うま',pre:'',post:' が はしる',mean:'どうぶつ'},{g:2,k:'歩く',r:'あるく',pre:'みちを ',post:'',mean:'足で すすむ'},{g:2,k:'走る',r:'はしる',pre:'校ていを ',post:'',mean:'はやく すすむ'},{g:2,k:'近い',r:'ちかい',pre:'家が ',post:'',mean:'きょりが みじかい'},{g:2,k:'遠い',r:'とおい',pre:'駅が ',post:'',mean:'きょりが ながい'},{g:2,k:'高い',r:'たかい',pre:'',post:' 山',mean:'上まで 大きい'},{g:2,k:'新しい',r:'あたらしい',pre:'',post:' 本',mean:'できた ばかり'},{g:2,k:'読む',r:'よむ',pre:'本を ',post:'',mean:'文字を こえに する'},{g:2,k:'書く',r:'かく',pre:'字を ',post:'',mean:'文字を しるす'},{g:2,k:'聞く',r:'きく',pre:'話を ',post:'',mean:'耳で うける'},{g:2,k:'考える',r:'かんがえる',pre:'こたえを ',post:'',mean:'あたまで くらべる'},{g:2,k:'雲',r:'くも',pre:'白い ',post:' が うかぶ',mean:'空に うかぶ もの'},{g:2,k:'風',r:'かぜ',pre:'つよい ',post:' が ふく',mean:'空気の ながれ'},{g:2,k:'星',r:'ほし',pre:'よぞらの ',post:'',mean:'夜に ひかる もの'},{g:2,k:'海',r:'うみ',pre:'',post:' で およぐ',mean:'ひろい しおみず'},{g:2,k:'岩',r:'いわ',pre:'大きな ',post:'',mean:'とても 大きな 石'},{g:2,k:'弟',r:'おとうと',pre:'',post:' と あそぶ',mean:'年下の 男の きょうだい'},{g:2,k:'妹',r:'いもうと',pre:'',post:' と うたう',mean:'年下の 女の きょうだい'},{g:2,k:'兄',r:'あに',pre:'',post:' に ならう',mean:'年上の 男の きょうだい'},{g:2,k:'姉',r:'あね',pre:'',post:' と 出かける',mean:'年上の 女の きょうだい'},{g:2,k:'声',r:'こえ',pre:'大きな ',post:' で うたう',mean:'口から 出る 音'},{g:2,k:'顔',r:'かお',pre:'',post:' を あらう',mean:'目や 口が ある ところ'},{g:2,k:'体',r:'からだ',pre:'',post:' を うごかす',mean:'あたまから 足まで ぜんぶ'},{g:2,k:'教える',r:'おしえる',pre:'かん字を ',post:'',mean:'わかるように つたえる'},{g:2,k:'帰る',r:'かえる',pre:'家に ',post:'',mean:'もとの ばしょに もどる'},{g:2,k:'作る',r:'つくる',pre:'おかしを ',post:'',mean:'ざいりょうから こしらえる'},{g:2,k:'楽しい',r:'たのしい',pre:'',post:' 時間',mean:'うれしい きもち'},{g:2,k:'明るい',r:'あかるい',pre:'',post:' へや',mean:'ひかりが ある'},{g:2,k:'強い',r:'つよい',pre:'',post:' ちから',mean:'よわくない'},
  {g:3,k:'漢字',r:'かんじ',pre:'',post:' を おぼえる',mean:'日本語の 文字'},{g:3,k:'病院',r:'びょういん',pre:'',post:' へ 行く',mean:'びょうきを みる ところ'},{g:3,k:'薬',r:'くすり',pre:'',post:' を のむ',mean:'からだを よくする もの'},{g:3,k:'医者',r:'いしゃ',pre:'',post:' に みてもらう',mean:'びょうきを みる ひと'},{g:3,k:'神社',r:'じんじゃ',pre:'',post:' へ 行く',mean:'おまいりする ところ'},{g:3,k:'研究',r:'けんきゅう',pre:'虫を ',post:' する',mean:'くわしく しらべる'},{g:3,k:'宿題',r:'しゅくだい',pre:'',post:' を する',mean:'家でする べんきょう'},{g:3,k:'運動',r:'うんどう',pre:'',post:' を する',mean:'からだを うごかす'},{g:3,k:'始める',r:'はじめる',pre:'会を ',post:'',mean:'スタートする'},{g:3,k:'終わる',r:'おわる',pre:'じゅぎょうが ',post:'',mean:'おしまいに なる'},{g:3,k:'急ぐ',r:'いそぐ',pre:'駅へ ',post:'',mean:'はやく する'},{g:3,k:'泳ぐ',r:'およぐ',pre:'プールで ',post:'',mean:'水の 中を すすむ'},{g:3,k:'橋',r:'はし',pre:'',post:' を わたる',mean:'川などを こえる もの'},{g:3,k:'湖',r:'みずうみ',pre:'',post:' を 見る',mean:'大きな 水たまり'},{g:3,k:'祭り',r:'まつり',pre:'',post:' に 行く',mean:'みんなで たのしむ 行事'},{g:3,k:'緑',r:'みどり',pre:'',post:' の 葉',mean:'草や 葉の 色'},{g:3,k:'短い',r:'みじかい',pre:'',post:' えんぴつ',mean:'ながくない'},{g:3,k:'深い',r:'ふかい',pre:'',post:' 池',mean:'そこまで とおい'},{g:3,k:'世界',r:'せかい',pre:'',post:' を 知る',mean:'たくさんの 国や 人'},{g:3,k:'写真',r:'しゃしん',pre:'',post:' を とる',mean:'カメラで うつした もの'},{g:3,k:'図書館',r:'としょかん',pre:'',post:' で 本を かりる',mean:'本が たくさん ある ところ'},{g:3,k:'駅',r:'えき',pre:'',post:' で 電車に のる',mean:'電車が とまる ところ'},{g:3,k:'旅行',r:'りょこう',pre:'家族で ',post:' に 行く',mean:'とおくへ 出かける こと'},{g:3,k:'練習',r:'れんしゅう',pre:'サッカーの ',post:'',mean:'くりかえし ならう こと'},{g:3,k:'勉強',r:'べんきょう',pre:'',post:' を がんばる',mean:'学んで 力を つける こと'},{g:3,k:'動物',r:'どうぶつ',pre:'',post:' の せわを する',mean:'生きて うごく もの'},{g:3,k:'昔',r:'むかし',pre:'',post:' の 話を 聞く',mean:'ずっと まえの こと'},{g:3,k:'荷物',r:'にもつ',pre:'おもい ',post:' を はこぶ',mean:'もちはこぶ もの'},{g:3,k:'港',r:'みなと',pre:'',post:' に ふねが つく',mean:'ふねが とまる ところ'},{g:3,k:'島',r:'しま',pre:'小さな ',post:' に わたる',mean:'海に かこまれた りく'},{g:3,k:'坂',r:'さか',pre:'',post:' を のぼる',mean:'かたむいた みち'},{g:3,k:'柱',r:'はしら',pre:'家の ',post:'',mean:'たてものを ささえる もの'},{g:3,k:'洋服',r:'ようふく',pre:'あたらしい ',post:'',mean:'きる もの'},{g:3,k:'悲しい',r:'かなしい',pre:'',post:' 気もち',mean:'なきたく なる 気もち'},{g:3,k:'重い',r:'おもい',pre:'',post:' かばん',mean:'かるくない'},{g:3,k:'速い',r:'はやい',pre:'',post:' 電車',mean:'スピードが ある'}
];const pool=L.filter(x=>x.g<=g);const early=stage<=2?pool.filter(x=>x.g===1):(stage>=5?pool.filter(x=>x.g===g):pool);const use=early.length?early:pool;const it=use[this.rand(0,use.length-1)];const choose=stage>=5||(stage>=3&&Math.random()<0.5);const others=this.shuffle(use.filter(x=>x.k!==it.k));if(choose){const choices=this.shuffle([it.k].concat(others.slice(0,3).map(x=>x.k)));return{topic:'kokugo',mode:'choices',isKokugo:true,subtype:'kanji-choice',pre:it.pre,word:it.r,post:it.post,mean:'あう かんじを えらぼう',prompt:it.pre+it.r+it.post,answer:it.k,choices:choices,explanation:'「'+it.r+'」は 「'+it.k+'」と 書くよ。いみ：'+it.mean};}const choices=this.shuffle([it.r].concat(others.filter(x=>x.r!==it.r).slice(0,3).map(x=>x.r)));return{topic:'kokugo',mode:'choices',isKokugo:true,subtype:'reading',pre:it.pre,word:it.k,post:it.post,mean:it.mean,prompt:it.pre+it.k+it.post,answer:it.r,choices:choices,explanation:'「'+it.k+'」は 「'+it.r+'」と よむよ。いみ：'+it.mean};}
  pickMoji(p){const stage=this.topicStage(p,'moji');const alphabet=[
    ['A','エー'],['B','ビー'],['C','シー'],['D','ディー'],['E','イー'],['F','エフ'],['G','ジー'],['H','エイチ'],['I','アイ'],['J','ジェイ'],['K','ケー'],['L','エル'],['M','エム'],['N','エヌ'],['O','オー'],['P','ピー'],['Q','キュー'],['R','アール'],['S','エス'],['T','ティー'],['U','ユー'],['V','ブイ'],['W','ダブリュー'],['X','エックス'],['Y','ワイ'],['Z','ゼット']
  ];const hira=[
    ['あ','ア'],['い','イ'],['う','ウ'],['え','エ'],['お','オ'],['か','カ'],['き','キ'],['く','ク'],['け','ケ'],['こ','コ'],['さ','サ'],['し','シ'],['す','ス'],['せ','セ'],['そ','ソ'],['た','タ'],['ち','チ'],['つ','ツ'],['て','テ'],['と','ト'],['な','ナ'],['に','ニ'],['ぬ','ヌ'],['ね','ネ'],['の','ノ'],['は','ハ'],['ひ','ヒ'],['ふ','フ'],['へ','ヘ'],['ほ','ホ'],['ま','マ'],['み','ミ'],['む','ム'],['め','メ'],['も','モ'],['や','ヤ'],['ゆ','ユ'],['よ','ヨ'],['ら','ラ'],['り','リ'],['る','ル'],['れ','レ'],['ろ','ロ'],['わ','ワ'],['を','ヲ'],['ん','ン']
  ];const romaji=[['a','あ'],['i','い'],['u','う'],['e','え'],['o','お'],['ka','か'],['ki','き'],['ku','く'],['ke','け'],['ko','こ'],['sa','さ'],['shi','し'],['su','す'],['se','せ'],['so','そ'],['ta','た'],['chi','ち'],['tsu','つ'],['te','て'],['to','と'],['na','な'],['ni','に'],['ne','ね'],['no','の'],['ha','は'],['hi','ひ'],['fu','ふ'],['ho','ほ'],['ma','ま'],['mi','み'],['mu','む'],['me','め'],['mo','も'],['ya','や'],['yu','ゆ'],['yo','よ'],['ra','ら'],['ri','り'],['ru','る'],['re','れ'],['ro','ろ'],['wa','わ'],['n','ん']];let kinds=stage<=1?['hiragana']:stage===2?['hiragana','katakana','kotoba']:stage>=5?['kotoba','kotoba','alphabet']:['hiragana','katakana','alphabet','alphabet','kotoba'];const gm=this.effectiveGrade(p);if(gm>=3&&stage>=3)kinds=kinds.concat(stage>=5?['romaji','romaji','romaji']:['romaji','romaji']);const subtype=kinds[this.rand(0,kinds.length-1)];if(subtype==='kotoba'){const W=[
    ['がっこう','がつこう','がここう','がっこお','べんきょうする ところ'],
    ['きって','きつて','きて','きっで','てがみに はる もの'],
    ['ざっし','ざつし','ざし','ざっしい','しゃしんや きじが のった 本'],
    ['らっぱ','らつぱ','らぱ','らっぷ','ぷーっと ならす がっき'],
    ['でんしゃ','でんしや','でんさや','てんしゃ','せんろを はしる のりもの'],
    ['きんぎょ','きんぎよ','きんきょ','ぎんぎょ','あかい ちいさな さかな'],
    ['おちゃ','おちや','おっちゃ','おちゃあ','きゅうすで いれる のみもの'],
    ['じてんしゃ','じてんしや','じでんしゃ','じてんさ','ペダルを こいで すすむ のりもの'],
    ['おかあさん','おかーさん','おかさん','おがあさん','やさしい かぞく（女の人）'],
    ['おにいさん','おにーさん','おにさん','おねいさん','としうえの 男の きょうだい'],
    ['こおり','こうり','こおうり','こり','つめたい 水の かたまり'],
    ['とけい','とけえ','とっけい','どけい','じかんを しる どうぐ'],
    ['しゃしん','しやしん','さしん','しゃっしん','カメラで とる もの'],
    ['ぎゅうにゅう','ぎゆうにゆう','ぎゅうにゅ','ぎゅーにゅー','うしから とれる のみもの']
  ];const it=W[this.rand(0,W.length-1)];return{topic:'moji',mode:'choices',subtype:'kotoba',prompt:it[4]+'。ただしい かきかたは どれ？',answer:it[0],choices:this.shuffle(it.slice(0,4)),explanation:'ただしくは 「'+it[0]+'」と かくよ。'};}if(subtype==='romaji'){const it=romaji[this.rand(0,romaji.length-1)],others=this.shuffle(romaji.filter(x=>x[1]!==it[1]));return{topic:'moji',mode:'choices',subtype:'romaji',prompt:'ローマ字「'+it[0]+'」は ひらがなで？',answer:it[1],choices:this.shuffle([it[1]].concat(others.slice(0,3).map(x=>x[1]))),explanation:'ローマ字「'+it[0]+'」は 「'+it[1]+'」と よむよ。'};}if(subtype==='alphabet'){const it=alphabet[this.rand(0,alphabet.length-1)],others=this.shuffle(alphabet.filter(x=>x[0]!==it[0]));return{topic:'moji',mode:'choices',subtype:'alphabet',prompt:'アルファベット「'+it[0]+'」の よみは？',answer:it[1],choices:this.shuffle([it[1]].concat(others.slice(0,3).map(x=>x[1]))),explanation:'「'+it[0]+'」は 「'+it[1]+'」と よむよ。'};}const it=hira[this.rand(0,hira.length-1)],others=this.shuffle(hira.filter(x=>x[0]!==it[0]));if(subtype==='katakana'){return{topic:'moji',mode:'choices',subtype:'katakana',prompt:'ひらがな「'+it[0]+'」と おなじ カタカナは？',answer:it[1],choices:this.shuffle([it[1]].concat(others.slice(0,3).map(x=>x[1]))),explanation:'「'+it[0]+'」は カタカナで 「'+it[1]+'」。'};}return{topic:'moji',mode:'choices',subtype:'hiragana',prompt:'カタカナ「'+it[1]+'」と おなじ ひらがなは？',answer:it[0],choices:this.shuffle([it[0]].concat(others.slice(0,3).map(x=>x[0]))),explanation:'「'+it[1]+'」は ひらがなで 「'+it[0]+'」。'};}
  pickBun(p){const g=this.effectiveGrade(p),stage=this.topicStage(p,'bun');const mc=(pr,ans,pool,ex)=>({topic:'bun',mode:'choices',prompt:pr,answer:ans,choices:this.pick4(ans,pool),explanation:ex});const Q=[];
    const J=[['わたし（　）えほんを よむ','は','くっつきの「は」。「わ」と よむけど 「は」と 書くよ。'],['ぼく（　）一ねんせいです','は','くっつきの「は」。「わ」と よむけど 「は」と 書くよ。'],['おかあさん（　）やさしい','は','くっつきの「は」。「わ」と よむけど 「は」と 書くよ。'],['りんご（　）たべる','を','「なにを」の ときは 「を」を つかうよ。'],['みず（　）のむ','を','「なにを」の ときは 「を」を つかうよ。'],['えほん（　）よむ','を','「なにを」の ときは 「を」を つかうよ。'],['ボール（　）なげる','を','「なにを」の ときは 「を」を つかうよ。'],['がっこう（　）いく','へ','いく ばしょには 「へ」。「え」と よむけど 「へ」と 書くよ。'],['こうえん（　）いく','へ','いく ばしょには 「へ」。「え」と よむけど 「へ」と 書くよ。'],['おばあさんの いえ（　）いく','へ','いく ばしょには 「へ」。「え」と よむけど 「へ」と 書くよ。']];
    Q.push(()=>{const it=J[this.rand(0,J.length-1)];const wrong={'は':'わ','を':'お','へ':'え'}[it[1]];return mc(it[0]+'　（　）に はいる じは？',it[1],['は','を','へ'].filter(x=>x!==it[1]).concat([wrong]),it[2]);});
    if(stage>=2||g>=2){
    Q.push(()=>mc('ぶんの おわりに つける 「。」の なまえは？','まる（くてん）',['てん（とうてん）','かぎかっこ','なかてん'],'ぶんの おわりには 「。」（まる）を つけるよ。'));
    Q.push(()=>mc('ぶんの とちゅうの くぎりに つける 「、」の なまえは？','てん（とうてん）',['まる（くてん）','かぎかっこ','はてな'],'ぶんの とちゅうには 「、」（てん）を つけるよ。'));
    Q.push(()=>mc('はなした ことばに つける しるしは？','「　」（かぎかっこ）',['。（まる）','、（てん）','・（なかてん）'],'はなした ことばは 「　」（かぎかっこ）で かこむよ。'));
    Q.push(()=>mc('ただしい ぶんは どれ？','「おはよう。」と いった。',['おはよう。と いった。','「おはよう」。と いった','おはよう と。いった。'],'はなした ことばは 「　」で かこんで、おわりに 「。」を つけるよ。'));
    }
    if(g>=2){
    const K=[['ぱん','パン','がいこくから きた ことば'],['けーき','ケーキ','がいこくから きた ことば'],['ばす','バス','がいこくから きた ことば'],['てれび','テレビ','がいこくから きた ことば'],['じゅーす','ジュース','がいこくから きた ことば'],['ぴあの','ピアノ','がいこくから きた ことば'],['わんわん','ワンワン','どうぶつの なきごえ'],['にゃーにゃー','ニャーニャー','どうぶつの なきごえ'],['がちゃん','ガチャン','ものの 音'],['あめりか','アメリカ','がいこくの 国や 土地の 名前']];
    Q.push(()=>{const it=K[this.rand(0,K.length-1)];return mc('「'+it[0]+'」の ただしい 書きかたは？',it[1],[it[0]],it[2]+'だから カタカナで 「'+it[1]+'」と 書くよ。');});
    Q.push(()=>{const it=K[this.rand(0,K.length-1)];const native=this.shuffle(['やま','かわ','はな','そら','うみ','いし']).slice(0,3);return mc('カタカナで 書く ことばは どれ？',it[0],native,'「'+it[0]+'」は '+it[2]+'だから カタカナで 「'+it[1]+'」と 書くよ。');});
    const SJ=[['犬が','走る','元気に','犬が 元気に 走る。'],['花が','さく','庭で','庭で 花が さく。'],['雨が','ふる','朝から','朝から 雨が ふる。'],['鳥が','とぶ','空を','空を 鳥が とぶ。'],['弟が','わらう','にこにこ','弟が にこにこ わらう。'],['先生が','話す','しずかに','先生が しずかに 話す。'],['ねこが','ねる','まどべで','ねこが まどべで ねる。']];
    Q.push(()=>{const it=SJ[this.rand(0,SJ.length-1)];const isShu=Math.random()<0.5;const ans=isShu?it[0]:it[1];return mc('「'+it[3]+'」の '+(isShu?'しゅご（だれが・なにが）':'じゅつご（どうする）')+'は？',ans,[isShu?it[1]:it[0],it[2]],isShu?'「だれが・なにが」に あたる ことばが しゅご。「'+it[0]+'」だね。':'「どうする」に あたる ことばが じゅつご。「'+it[1]+'」だね。');});
    }
    if(g>=3){
    const SH=[['大きな','犬',['歩く','ゆっくり'],'大きな 犬が ゆっくり 歩く。'],['白い','花',['さいた','庭に'],'庭に 白い 花が さいた。'],['ゆっくり','歩く',['犬が','大きな'],'大きな 犬が ゆっくり 歩く。'],['きれいな','声',['うたう','姉が'],'姉が きれいな 声で うたう。'],['あまい','ケーキ',['食べた','おやつに'],'おやつに あまい ケーキを 食べた。'],['はやく','走る',['うさぎが','野原を'],'うさぎが 野原を はやく 走る。']];
    Q.push(()=>{const it=SH[this.rand(0,SH.length-1)];return mc('「'+it[3]+'」で 「'+it[0]+'」が くわしく して いる ことばは？',it[1],it[2],'「'+it[0]+'」は 「'+it[1]+'」を くわしく する ことば（しゅうしょくご）だよ。');});
    }
    return Q[this.rand(0,Q.length-1)]();}
  pickGoi(p){const g=this.effectiveGrade(p),stage=this.topicStage(p,'goi');const mc=(pr,ans,pool,ex)=>({topic:'goi',mode:'choices',prompt:pr,answer:ans,choices:this.pick4(ans,pool),explanation:ex});const Q=[];
    const H=[['大きい','小さい'],['たかい','ひくい'],['ながい','みじかい'],['あつい','さむい'],['はやい','おそい'],['あかるい','くらい'],['おもい','かるい'],['つよい','よわい'],['ひろい','せまい'],['あたらしい','ふるい'],['うえ','した'],['まえ','うしろ'],['みぎ','ひだり'],['あさ','よる'],['いく','くる'],['あける','しめる']];
    Q.push(()=>{const it=H[this.rand(0,H.length-1)];const flip=Math.random()<0.5;const w=flip?it[1]:it[0],ans=flip?it[0]:it[1];const others=this.shuffle(H.filter(x=>x!==it)).slice(0,3).map(x=>x[this.rand(0,1)]);return mc('「'+w+'」の はんたいの ことばは？',ans,others,'「'+w+'」の はんたいは 「'+ans+'」だよ。');});
    const N=[['くだもの',['りんご','みかん','ばなな','ぶどう']],['どうぶつ',['いぬ','ねこ','うま','ぞう']],['のりもの',['バス','でんしゃ','ふね','ひこうき']],['やさい',['にんじん','だいこん','きゅうり','なす']],['いろ',['あか','あお','しろ','きいろ']],['てんき',['はれ','あめ','くもり','ゆき']]];
    Q.push(()=>{const it=N[this.rand(0,N.length-1)];const members=this.shuffle(it[1].slice()).slice(0,3);const others=this.shuffle(N.filter(x=>x!==it)).slice(0,3).map(x=>x[0]);return mc(members.join('・')+' は なんの なかま？',it[0],others,members.join('・')+' は みんな '+it[0]+' の なかまだよ。');});
    Q.push(()=>{const it=N[this.rand(0,N.length-1)];const other=this.shuffle(N.filter(x=>x!==it))[0];const odd=other[1][this.rand(0,other[1].length-1)];const members=this.shuffle(it[1].slice()).slice(0,3);return mc('なかまはずれは どれ？',odd,members,'「'+odd+'」は '+other[0]+'。ほかは みんな '+it[0]+' の なかまだよ。');});
    if(g>=3){
    const KW=[['さるも木から落ちる','じょうずな 人でも しっぱいする ことが ある'],['犬も歩けばぼうに当たる','出歩くと 思いがけない ことに 出会う'],['石の上にも三年','がまんして つづければ うまくいく'],['ねこの手もかりたい','とても いそがしい'],['花よりだんご','見た目より 役に立つ ものが よい'],['口がかるい','ひみつを すぐ 話して しまう'],['頭をひねる','いっしょうけんめい 考える'],['耳にたこができる','同じ 話を なんども 聞かされる'],['馬が合う','気が 合う'],['手をかす','手つだう']];
    Q.push(()=>{const it=KW[this.rand(0,KW.length-1)];const others=this.shuffle(KW.filter(x=>x!==it)).slice(0,3).map(x=>x[1]);return mc('「'+it[0]+'」の いみは？',it[1],others,'「'+it[0]+'」は 「'+it[1]+'」と いう いみだよ。');});
    const JW=['あき','あさ','あめ','いえ','いぬ','いす','うた','うみ','えき','かい','かき','かさ','きた','くも','さかな','しか','すいか','そら','たけ','つき','ねこ','はし','はな','ふね','ほし','みかん','むし','やま','ゆき'];
    Q.push(()=>{const ws=this.shuffle(JW.slice()).slice(0,3);const sorted=ws.slice().sort();const first=Math.random()<0.5;const ans=first?sorted[0]:sorted[2];return{topic:'goi',mode:'choices',prompt:ws.join('・')+' を 国語じてんの じゅんに ならべると、いちばん '+(first?'はじめ':'あと')+'に 出てくるのは？',answer:ans,choices:this.shuffle(ws.slice()),explanation:'五十音じゅんに ならべると '+sorted.join('→')+' だよ。'};});
    }
    return Q[this.rand(0,Q.length-1)]();}
  pickDokkai(p){const g=this.effectiveGrade(p),stage=this.topicStage(p,'dokkai');const D=[
    {g:1,t:'ねこが にわで ねて います。いぬが その よこで あそんで います。',q:'ねこは どこに いますか？',a:'にわ',c:['いえの 中','こうえん','やねの 上'],e:'「ねこが にわで ねて います」と 書いて あるよ。'},
    {g:1,t:'たろうは あさ パンを たべました。それから がっこうへ いきました。',q:'たろうが たべた ものは？',a:'パン',c:['ごはん','みかん','たまご'],e:'はじめの ぶんに 「パンを たべました」と あるよ。'},
    {g:1,t:'はなこは あかい ぼうしを かぶって、こうえんへ いきました。',q:'ぼうしの いろは？',a:'あか',c:['あお','しろ','きいろ'],e:'「あかい ぼうし」と 書いて あるよ。'},
    {g:1,t:'きのうは あめが ふりました。きょうは はれて います。',q:'きょうの てんきは？',a:'はれ',c:['あめ','ゆき','くもり'],e:'「きょうは はれて います」と あるよ。'},
    {g:1,t:'みかんが 3こ、りんごが 2こ あります。',q:'おおい くだものは どっち？',a:'みかん',c:['りんご'],e:'みかんは 3こ、りんごは 2こ。3こ の ほうが おおいね。'},
    {g:1,t:'ゆうとは いぬと いっしょに かわへ いきました。',q:'ゆうとは どこへ いった？',a:'かわ',c:['うみ','やま','がっこう'],e:'「かわへ いきました」と 書いて あるよ。'},
    {g:2,t:'日曜日、かなは 家ぞくと 海へ 行きました。かなは きれいな 貝を 三つ ひろいました。',q:'かなが ひろった ものは？',a:'貝',c:['石','花','魚'],e:'「貝を 三つ ひろいました」と あるよ。'},
    {g:2,t:'けんたは 朝 早く おきて、犬の さんぽに 行きました。とちゅうで 友だちの ゆきさんに 会いました。',q:'けんたが 会ったのは だれ？',a:'ゆきさん',c:['先生','お母さん','おじいさん'],e:'「友だちの ゆきさんに 会いました」と あるよ。'},
    {g:2,t:'学校の 帰りに 雨が ふって きました。ぼくは かさが なかったので、走って 家に 帰りました。',q:'ぼくが 走った わけは？',a:'かさが なかったから',c:['あそびたかったから','おなかが すいたから','さむかったから'],e:'「かさが なかったので、走って」と あるよ。'},
    {g:2,t:'みほは 花だんに 花の たねを まきました。まい日 水を やると、小さな めが 出ました。',q:'めが 出るまで みほが まい日 した ことは？',a:'水を やった',c:['たねを まいた','花を つんだ','土を ほった'],e:'「まい日 水を やると、めが 出ました」と あるよ。'},
    {g:2,t:'たけしは 本が すきです。としょかんで 毎週 二さつ かりて、ねる 前に 読みます。',q:'たけしが 本を 読むのは いつ？',a:'ねる 前',c:['朝ごはんの 前','学校の 帰り','昼休み'],e:'「ねる 前に 読みます」と あるよ。'},
    {g:3,t:'図書館で 本を かりるには、カードが いります。カードは うけつけで 作って もらえます。',q:'カードを 作れる ばしょは？',a:'うけつけ',c:['学校','ゆうびんきょく','本だな'],e:'「カードは うけつけで 作って もらえます」と あるよ。'},
    {g:3,t:'ひまわりは 夏に さく 花です。せが 高く のびて、太陽の ほうを むいて さきます。',q:'ひまわりが さく きせつは？',a:'夏',c:['春','秋','冬'],e:'「ひまわりは 夏に さく 花です」と あるよ。'},
    {g:3,t:'ペンギンは 鳥の なかまですが、空を とぶ ことは できません。そのかわり、海の 中を じょうずに およぎます。',q:'ペンギンが じょうずに できる ことは？',a:'およぐ こと',c:['とぶ こと','木に のぼる こと','あなを ほる こと'],e:'「海の 中を じょうずに およぎます」と あるよ。'},
    {g:3,t:'あすかは 九時に ねて、六時に おきます。朝ごはんの 前に、なわとびを 五十回 とびます。',q:'あすかが 朝ごはんの 前に する ことは？',a:'なわとび',c:['さんぽ','べんきょう','そうじ'],e:'「朝ごはんの 前に、なわとびを」と あるよ。'},
    {g:3,t:'カブトムシは 夜に なると 木に あつまり、木の しるを なめます。昼の あいだは 土の 中で 休んで います。',q:'カブトムシが 昼に いる ばしょは？',a:'土の 中',c:['木の 上','空','水の 中'],e:'「昼の あいだは 土の 中で 休んで います」と あるよ。'}
  ];const pool=D.filter(x=>x.g<=g);const early=stage<=2?pool.filter(x=>x.g===1):(stage>=5?pool.filter(x=>x.g===g):pool);const use=early.length?early:pool;const it=use[this.rand(0,use.length-1)];return{topic:'dokkai',mode:'choices',prompt:it.t+'　◆　'+it.q,answer:it.a,choices:this.pick4(it.a,it.c),explanation:it.e};}
  pickEigo(p){const stage=this.topicStage(p,'eigo');const mc=(pr,ans,pool,ex,speak)=>({topic:'eigo',mode:'choices',prompt:pr,answer:ans,choices:this.pick4(ans,pool),explanation:ex,speakChoices:!!speak});const Q=[];
    const wq=L=>{const it=L[this.rand(0,L.length-1)],others=this.shuffle(L.filter(x=>x[0]!==it[0]));if(Math.random()<0.5)return mc('英語「'+it[0]+'」の いみは？',it[1],others.slice(0,3).map(x=>x[1]),'「'+it[0]+'」は 「'+it[1]+'」だよ。',false);return mc('「'+it[1]+'」を 英語で いうと？',it[0],others.slice(0,3).map(x=>x[0]),'「'+it[1]+'」は 英語で 「'+it[0]+'」。',true);};
    const C=[['red','あか'],['blue','あお'],['yellow','きいろ'],['green','みどり'],['black','くろ'],['white','しろ'],['pink','ピンク'],['orange','オレンジいろ'],['purple','むらさき'],['brown','ちゃいろ']];
    const NUM=[['one','1'],['two','2'],['three','3'],['four','4'],['five','5'],['six','6'],['seven','7'],['eight','8'],['nine','9'],['ten','10']];
    Q.push(()=>wq(C));
    Q.push(()=>wq(NUM));
    if(stage>=2){
    const W=[['dog','いぬ'],['cat','ねこ'],['bird','とり'],['fish','さかな'],['rabbit','うさぎ'],['monkey','さる'],['bear','くま'],['horse','うま'],['apple','りんご'],['banana','バナナ'],['milk','ぎゅうにゅう'],['egg','たまご'],['rice','ごはん'],['book','本'],['pen','ペン'],['bag','かばん'],['cap','ぼうし'],['ball','ボール'],['hand','て'],['eye','め']];
    Q.push(()=>wq(W));
    Q.push(()=>wq(W));
    }
    if(stage>=3){
    const G=[['あさ 会ったときの あいさつは？','Good morning.',['Good night.','Thank you.','Goodbye.'],'あさの あいさつは Good morning. だよ。'],
    ['ねる まえの あいさつは？','Good night.',['Good morning.','Hello.','Thank you.'],'ねる まえは Good night. だよ。'],
    ['「ありがとう」を 英語で いうと？','Thank you.',['Sorry.','Hello.','Goodbye.'],'ありがとうは Thank you. だよ。'],
    ['わかれる ときの あいさつは？','Goodbye.',['Hello.','Good morning.','Thank you.'],'わかれる ときは Goodbye. だよ。'],
    ['「こんにちは」に あたる あいさつは？','Hello.',['Goodbye.','Good night.','Sorry.'],'こんにちはは Hello. だよ。'],
    ['なまえを きく いいかたは？','What is your name?',['How are you?','How old are you?','What color do you like?'],'なまえを きくときは What is your name? だよ。'],
    ['「げんきですか」と きく いいかたは？','How are you?',['What is your name?','Good night.','See you.'],'げんきかどうかは How are you? と きくよ。']];
    Q.push(()=>{const it=G[this.rand(0,G.length-1)];return mc(it[0],it[1],it[2],it[3],true);});
    }
    if(stage>=4){const S=[['I like apples.','わたしは りんごが すきです。'],['I have a dog.','わたしは いぬを かっています。'],['This is my book.','これは わたしの 本です。'],['I can swim.','わたしは およげます。']];Q.push(()=>wq(S));}
    if(stage>=5){const R=[['How are you?','I am fine.',['Good night.','My name is Ken.','Thank you.']],['What is your name?','My name is Ken.',['I am ten.','Good morning.','I like blue.']],['What color do you like?','I like blue.',['I am fine.','See you.','It is a dog.']]];Q.push(()=>{const it=R[this.rand(0,R.length-1)];return mc('しつもん「'+it[0]+'」に あう こたえは？',it[1],it[2],it[0]+' には '+it[1]+' と こたえるよ。',true);});}
    const q=Q[this.rand(0,Q.length-1)]();q.difficulty=stage;return q;}
""";
    }
}
