namespace KidsTraining.App.Application.Learning.Markup;

internal static partial class LearningMarkupPatcher
{
    private static string BuildLearningNotationScript()
    {
        return """
  notationIsAsciiLetter(ch){return !!ch&&/[A-Za-z]/.test(ch);}
  notationIsOperand(text,index){const ch=text[index]||'';if(/[0-9π□²³)\]}]/.test(ch))return true;if(!this.notationIsAsciiLetter(ch))return false;return !this.notationIsAsciiLetter(text[index-1])&&!this.notationIsAsciiLetter(text[index+1]);}
  notationNeighbor(text,index,direction){let cursor=index+direction;while(/\s/.test(text[cursor]||''))cursor+=direction;return{index:cursor,ch:text[cursor]||'',operand:this.notationIsOperand(text,cursor)};}
  notationFractionAt(text,index){const match=text.slice(index).match(/^((?:(?:\d+(?:\.\d+)?|[A-Za-zπ□])(?:[×*](?:\d+(?:\.\d+)?|[A-Za-zπ□]))*)\/(?:\d+(?:\.\d+)?|[A-Za-zπ□]))/);if(!match)return null;const source=match[1],before=text[index-1]||'',after=text[index+source.length]||'';if(/[A-Za-z0-9]/.test(before)||/[A-Za-z0-9]/.test(after))return null;const slash=source.lastIndexOf('/');return{source:source,numerator:source.slice(0,slash),denominator:source.slice(slash+1)};}
  notationRatioAt(text,index){const match=text.slice(index).match(/^(\d+(?:\.\d+)?)([:：])(\d+(?:\.\d+)?)/);if(!match)return null;const source=match[0],before=text[index-1]||'',after=text[index+source.length]||'';if(/[A-Za-z0-9]/.test(before)||/[A-Za-z0-9]/.test(after))return null;return{source:source,left:match[1],mark:match[2],right:match[3]};}
  notationUnaryAt(text,index){const ch=text[index]||'',before=this.notationNeighbor(text,index,-1),after=this.notationNeighbor(text,index,1);return (ch==='-'||ch==='−')&&after.operand&&(!before.ch||before.ch==='='||before.ch==='('||before.ch==='['||before.ch==='{'||before.ch===','||before.ch==='、'||before.ch===';'||before.ch==='；'||before.ch===':'||before.ch==='：'||before.ch==='+'||before.ch==='−'||before.ch==='-'||before.ch==='±');}
  notationOperatorAt(text,index){const ch=text[index]||'',before=this.notationNeighbor(text,index,-1),after=this.notationNeighbor(text,index,1),prev=before.operand,next=after.operand;if(ch==='-'||ch==='−')return (prev&&next)||this.notationUnaryAt(text,index);if(ch==='+'||ch==='*'||ch==='×'||ch==='÷'||ch==='='||ch==='<'||ch==='>'||ch==='≤'||ch==='≥'||ch==='±'){if(ch==='±'&&(before.ch==='='||before.ch==='(')&&next)return true;if(prev&&next)return true;if((ch==='='||ch==='±')&&(after.ch==='-'||after.ch==='−'||after.ch==='±'))return this.notationNeighbor(text,after.index,1).operand;}return false;}
  notationFraction(numerator,denominator,key){const label=denominator+'分の'+numerator;return React.createElement('span',{key:key,className:'kt-math kt-fraction',role:'math','aria-label':label,title:label},React.createElement('span',{className:'kt-fraction-numerator','aria-hidden':true},numerator),React.createElement('span',{className:'kt-fraction-denominator','aria-hidden':true},denominator));}
  notationRatio(left,mark,right,key){const label=left+'対'+right;return React.createElement('span',{key:key,className:'kt-math kt-ratio',role:'math','aria-label':label,title:label},React.createElement('span',{className:'kt-ratio-left','aria-hidden':true},left),React.createElement('span',{className:'kt-ratio-mark','aria-hidden':true},mark),React.createElement('span',{className:'kt-ratio-right','aria-hidden':true},right));}
  notationRadical(radicand,key){const label=radicand+'の平方根';return React.createElement('span',{key:key,className:'kt-math kt-radical',role:'math','aria-label':label,title:label},React.createElement('span',{className:'kt-radical-sign','aria-hidden':true},'√'),React.createElement('span',{className:'kt-radicand','aria-hidden':true},radicand));}
  notationSuperscript(base,power,key){const label=base+(power==='²'?'の2乗':'の3乗');return React.createElement('span',{key:key,className:'kt-math kt-power',role:'math','aria-label':label,title:label},React.createElement('span',{'aria-hidden':true},base),React.createElement('sup',{className:'kt-superscript','aria-hidden':true},power==='²'?'2':'3'));}
  notationOperator(op,key,unary){const labels={'+':'たす','−':unary?'マイナス':'ひく','×':'かける','÷':'わる','=':'イコール','<':'より小さい','>':'より大きい','≤':'以下','≥':'以上','±':'プラスマイナス'},label=labels[op]||op;return React.createElement('span',{key:key,className:'kt-math kt-math-operator',role:'math','aria-label':label,title:label},op);}
  richMathDelimiterAt(text,index){const pairs=[['\\[','\\]'],['\\(','\\)'],['$$','$$']];for(const pair of pairs){if(!text.startsWith(pair[0],index))continue;const end=text.indexOf(pair[1],index+pair[0].length);if(end>index+pair[0].length)return{source:text.slice(index,end+pair[1].length),body:text.slice(index+pair[0].length,end),end:end+pair[1].length};}if(text[index]!=='$'||text[index+1]==='$')return null;let end=index+1;while(end<text.length){if(text[end]==='$'&&text[end-1]!=='\\')break;if(text[end]==='\n')return null;end++;}if(end>index+1&&end<text.length&&!/^\s|\s$/.test(text.slice(index+1,end)))return{source:text.slice(index,end+1),body:text.slice(index+1,end),end:end+1};return null;}
  richTexLabel(tex){return String(tex).replace(/\\frac\{([^{}]+)\}\{([^{}]+)\}/g,'$2分の$1').replace(/\\sqrt\{([^{}]+)\}/g,'$1の平方根').replace(/\\times/g,'かける').replace(/\\div/g,'わる').replace(/\\cdot/g,'かける').replace(/\\pm/g,'プラスマイナス').replace(/\\le/g,'以下').replace(/\\ge/g,'以上').replace(/\\neq/g,'等しくない').replace(/\\pi/g,'円周率').replace(/\\Box/g,'四角').replace(/[{}\\]/g,' ').replace(/\s+/g,' ').trim()||'数式';}
  richTexNode(kind,children,key){return React.createElement('span',{key:key,className:'kt-math kt-tex-'+kind},children);}
  richTexParse(tex){let pos=0,key=0;const nextKey=()=>('tex-'+(key++));const parseGroup=()=>{if(tex[pos]!=='{')return null;pos++;const nodes=parseUntil('}');if(nodes===null||tex[pos]!=='}')return null;pos++;return nodes;};const parseCommand=()=>{pos++;const match=tex.slice(pos).match(/^[A-Za-z]+|^[,;:!]/);if(!match)return null;const command=match[0];pos+=command.length;const simple={times:'×',div:'÷',cdot:'·',pm:'±',le:'≤',ge:'≥',neq:'≠',pi:'π',Box:'□'};if(Object.prototype.hasOwnProperty.call(simple,command))return simple[command];if(command==='frac'){const top=parseGroup(),bottom=parseGroup();return top===null||bottom===null?null:React.createElement('span',{key:nextKey(),className:'kt-math kt-fraction kt-tex-fraction'},React.createElement('span',{className:'kt-fraction-numerator','aria-hidden':true},top),React.createElement('span',{className:'kt-fraction-denominator','aria-hidden':true},bottom));}if(command==='sqrt'){const body=parseGroup();return body===null?null:React.createElement('span',{key:nextKey(),className:'kt-math kt-radical kt-tex-radical'},React.createElement('span',{className:'kt-radical-sign','aria-hidden':true},'√'),React.createElement('span',{className:'kt-radicand','aria-hidden':true},body));}if(command==='text'||command==='mathrm'){const body=parseGroup();return body===null?null:this.richTexNode(command,body,nextKey());}if(command==='left'||command==='right'||command==='displaystyle'||command==='quad'||command==='qquad'||command===','||command===';'||command===':'||command==='!'){if(command==='left'||command==='right'){if(pos>=tex.length)return null;pos++;}return command==='quad'||command==='qquad'?'　':'';}return null;};const appendScript=(nodes,tag,body)=>{if(!nodes.length)return false;const base=nodes.pop();nodes.push(React.createElement('span',{key:nextKey(),className:'kt-math kt-tex-script'},base,React.createElement(tag,{className:'kt-tex-'+tag,'aria-hidden':true},body)));return true;};const parseUntil=stop=>{const nodes=[];while(pos<tex.length&&tex[pos]!==stop){const ch=tex[pos];if(ch==='{'||ch==='}')return null;if(ch==='\\'){const item=parseCommand();if(item===null)return null;nodes.push(item);continue;}if(ch==='^'||ch==='_'){pos++;const body=tex[pos]==='{'?parseGroup():pos<tex.length?[tex[pos++]]:null;if(body===null||!appendScript(nodes,ch==='^'?'sup':'sub',body))return null;continue;}nodes.push(ch);pos++;}return nodes;};const nodes=parseUntil('');return nodes===null||pos!==tex.length?null:nodes;}
  richMath(value,key,block){const nodes=this.richTexParse(value);if(nodes===null)return null;const label='数式 '+this.richTexLabel(value);return React.createElement('span',{key:key,className:'kt-math kt-rich-math'+(block?' kt-rich-math-block':''),role:'math','aria-label':label,title:label},nodes);}
  richInline(text,keyPrefix){const out=[];let plain='',i=0,key=0;const flush=()=>{if(plain){out.push(this.withFurigana(plain));plain='';}};const takeDelimited=(marker,tag,className)=>{if(!text.startsWith(marker,i))return false;const end=text.indexOf(marker,i+marker.length);if(end<0||end===i+marker.length)return false;flush();out.push(React.createElement(tag,{key:keyPrefix+'-'+(key++),className:className},this.richInline(text.slice(i+marker.length,end),keyPrefix+'-'+key)));i=end+marker.length;return true;};while(i<text.length){const math=this.richMathDelimiterAt(text,i);if(math){const node=this.richMath(math.body,keyPrefix+'-math-'+(key++),math.source.startsWith('\\[')||math.source.startsWith('$$'));if(node){flush();out.push(node);i=math.end;continue;}}if(text[i]==='`'){const end=text.indexOf('`',i+1);if(end>i+1){flush();out.push(React.createElement('code',{key:keyPrefix+'-'+(key++),className:'kt-rich-code'},text.slice(i+1,end)));i=end+1;continue;}}if((text.startsWith('**',i)||text.startsWith('__',i))&&takeDelimited(text.slice(i,i+2),'strong','kt-rich-strong'))continue;if((text[i]==='*'||text[i]==='_')&&takeDelimited(text[i],'em','kt-rich-emphasis'))continue;plain+=text[i];i++;}flush();return out;}
  withRichInline(source){if(source===null||source===undefined)return React.createElement(React.Fragment,null);if(Array.isArray(source)||React.isValidElement(source))return source;return React.createElement(React.Fragment,null,this.richInline(String(source),'rich-inline'));}
  withRichText(source){if(source===null||source===undefined)return React.createElement(React.Fragment,null);if(Array.isArray(source)||React.isValidElement(source))return source;const text=String(source),blocks=text.split(/\n{2,}/),nodes=[];let key=0;for(const block of blocks){const lines=block.split('\n'),heading=lines.length===1&&lines[0].match(/^(#{1,6})\s+(.+)$/),unordered=lines.length>0&&lines.every(line=>/^[-*+]\s+/.test(line)),ordered=lines.length>0&&lines.every(line=>/^\d+[.)]\s+/.test(line));if(heading){const level=Math.min(6,heading[1].length);nodes.push(React.createElement('h'+level,{key:'rich-h-'+(key++),className:'kt-rich-heading'},this.richInline(heading[2],'rich-h-'+key)));continue;}if(unordered||ordered){const items=lines.map((line,index)=>React.createElement('li',{key:'rich-li-'+key+'-'+index},this.richInline(line.replace(unordered?/^[-*+]\s+/:/^\d+[.)]\s+/,''),'rich-li-'+key+'-'+index)));nodes.push(React.createElement(ordered?'ol':'ul',{key:'rich-list-'+(key++),className:'kt-rich-list'},items));continue;}const inline=[];lines.forEach((line,index)=>{if(index)inline.push(React.createElement('br',{key:'rich-br-'+key+'-'+index}));inline.push(...this.richInline(line,'rich-p-'+key+'-'+index));});nodes.push(React.createElement('p',{key:'rich-p-'+(key++),className:'kt-rich-paragraph'},inline));}return React.createElement(React.Fragment,null,nodes);}
  withLearningNotation(value){if(value===null||value===undefined||Array.isArray(value)||React.isValidElement(value))return value;const text=String(value);let out=[],plain='',changed=false,i=0;const flush=()=>{if(plain){out.push(plain);plain='';}};while(i<text.length){const fraction=this.notationFractionAt(text,i);if(fraction){flush();out.push(this.notationFraction(fraction.numerator,fraction.denominator,'fraction-'+i));changed=true;i+=fraction.source.length;continue;}const ratio=this.notationRatioAt(text,i);if(ratio){flush();out.push(this.notationRatio(ratio.left,ratio.mark,ratio.right,'ratio-'+i));changed=true;i+=ratio.source.length;continue;}const radical=text[i]==='√'&&text.slice(i+1).match(/^(\d+(?:\.\d+)?|[A-Za-zπ])/);if(radical){flush();const radicand=radical[1];out.push(this.notationRadical(radicand,'radical-'+i));changed=true;i+=1+radicand.length;continue;}const power=(text[i+1]==='²'||text[i+1]==='³')&&(/[0-9A-Za-zπ□)]/.test(text[i]||''));if(power){flush();out.push(this.notationSuperscript(text[i],text[i+1],'power-'+i));changed=true;i+=2;continue;}if(this.notationOperatorAt(text,i)){flush();const sourceOp=text[i],op=sourceOp==='-'?'−':sourceOp==='*'?'×':sourceOp;out.push(this.notationOperator(op,'operator-'+i,this.notationUnaryAt(text,i)));changed=true;i++;continue;}plain+=text[i];i++;}flush();return changed?out:text;}
""";
    }

    private static string BuildLearningNotationStyles()
    {
        return """
<style id="kt-learning-notation">
  .kt-math { font-family: ui-rounded, "Arial Rounded MT Bold", "Noto Sans JP", sans-serif; font-variant-numeric: tabular-nums; }
  .kt-fraction { display:inline-grid; grid-template-rows:auto auto; vertical-align:middle; min-width:1.14em; margin:0 .07em; text-align:center; line-height:1.02; white-space:nowrap; }
  .kt-fraction-numerator { display:block; padding:0 .16em .06em; border-bottom:.075em solid currentColor; }
  .kt-fraction-denominator { display:block; padding:.06em .16em 0; }
  .kt-power { display:inline-flex; align-items:baseline; vertical-align:baseline; white-space:nowrap; }
  .kt-superscript { margin-left:.025em; font-size:.58em; font-weight:900; line-height:1; vertical-align:super; }
  .kt-radical { display:inline-flex; align-items:flex-start; vertical-align:middle; white-space:nowrap; line-height:1.02; }
  .kt-radical-sign { font-size:1.14em; line-height:.96; }
  .kt-radicand { border-top:.075em solid currentColor; padding:.03em .08em 0 .1em; }
  .kt-ratio { display:inline-flex; align-items:baseline; vertical-align:baseline; white-space:nowrap; }
  .kt-ratio-mark { padding:0 .08em; font-weight:900; }
  .kt-math-operator { display:inline-block; min-width:.45em; text-align:center; white-space:pre; }
  .kt-rich-math { display:inline-flex; align-items:baseline; gap:.02em; margin:0 .05em; white-space:nowrap; }
  .kt-rich-math-block { display:flex; width:max-content; max-width:100%; margin:.48em auto; justify-content:center; overflow-x:auto; }
  .kt-tex-script { display:inline-flex; align-items:baseline; }
  .kt-tex-sup,.kt-tex-sub { font-size:.62em; font-weight:900; line-height:1; }
  .kt-tex-sup { vertical-align:super; transform:translateY(-.38em); }
  .kt-tex-sub { vertical-align:sub; transform:translateY(.22em); }
  .kt-rich-paragraph { margin:.35em 0; }
  .kt-rich-heading { margin:.4em 0 .22em; font-size:1.05em; font-weight:900; line-height:1.2; }
  .kt-rich-list { margin:.35em 0; padding-inline-start:1.45em; text-align:left; }
  .kt-rich-code { padding:.08em .28em; border-radius:.3em; background:#f0e8da; font-family:ui-monospace, monospace; font-size:.88em; }
  @media (min-width:761px) and (max-height:700px) {
    div:has(> .kt-question-metadata):has(.kt-question-prompt .kt-rich-math) { box-sizing:border-box!important; height:100vh!important; min-height:100vh!important; padding:10px 32px!important; overflow:hidden!important; }
    .kt-feedback-screen:has(.kt-feedback-explanation .kt-rich-math) { box-sizing:border-box!important; min-height:100dvh!important; padding:12px var(--kt-space-6)!important; }
    div:has(> .kt-question-metadata):has(.kt-question-prompt .kt-rich-math) > .kt-question-metadata { display:grid!important; grid-template-columns:repeat(4,minmax(0,1fr)); gap:4px!important; margin-top:4px!important; align-items:stretch!important; }
    div:has(> .kt-question-metadata):has(.kt-question-prompt .kt-rich-math) > .kt-question-metadata > span { box-sizing:border-box!important; width:auto!important; height:32px!important; min-height:32px!important; padding:3px 6px!important; border-width:2px!important; border-radius:10px!important; font-size:12px!important; line-height:1.1!important; white-space:nowrap!important; overflow:hidden!important; text-overflow:ellipsis!important; }
    div:has(> .kt-question-metadata):has(.kt-question-prompt .kt-rich-math) > .kt-question-metadata + div { margin-top:4px!important; min-height:0!important; }
    .kt-question-prompt:has(.kt-rich-math) { padding:0 12px!important; margin:0 auto 2px!important; font-size:clamp(36px,7vh,42px)!important; line-height:1.25!important; }
    .kt-question-prompt:has(.kt-rich-math) .kt-rich-paragraph { margin:.05em 0!important; }
    .kt-choice-grid:has(.kt-rich-math) { gap:6px!important; margin-top:4px!important; }
    .kt-choice-grid:has(.kt-rich-math) .kt-choice-button { min-height:64px!important; padding:4px 14px!important; font-size:22px!important; line-height:1.2!important; }
    div:has(> .kt-question-metadata):has(.kt-question-prompt .kt-rich-math) > [role="button"][aria-label="答えと説明を見る"] { box-sizing:border-box!important; height:44px!important; min-height:44px!important; margin-top:4px!important; padding:4px 18px!important; font-size:14px!important; }
  }
  @media (max-width:480px) { .kt-fraction { margin:0 .045em; } .kt-fraction-numerator,.kt-fraction-denominator { padding-left:.1em; padding-right:.1em; } }
</style>
""";
    }
}
