using System.Globalization;
using System.Text.Json;
using KidsTraining.App.Domain.Learning;

namespace KidsTraining.App.Application.Learning.Markup;

internal static partial class LearningMarkupPatcher
{
    private static string BuildProgressionScript()
    {
        var catalog = CurriculumPolicy.AllUnits.Select(unit => new
        {
            id = unit.Id,
            subjectId = unit.SubjectId,
            topicId = unit.TopicId,
            label = unit.Label,
            grade = unit.Grade,
            order = unit.Order,
            prerequisites = unit.Prerequisites,
            generatorKey = unit.GeneratorKey,
            assessmentMode = unit.AssessmentMode,
            sourceReference = unit.SourceReference,
            questions = unit.Questions.Select(question => new
            {
                stage = question.Stage,
                prompt = question.Prompt,
                answer = question.Answer,
                distractors = question.Distractors,
                explanation = question.Explanation,
                activityPrompt = question.ActivityPrompt
            })
        });
        var catalogJson = JsonSerializer.Serialize(catalog);
        var catalogRevision = Convert.ToHexString(
            System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(catalogJson)))[..16];
        var catalogRevisionJson = JsonSerializer.Serialize(catalogRevision);
        var lanesJson = JsonSerializer.Serialize(CurriculumPolicy.CurriculumLanes);
        var reviewIntervals = string.Join(',', Enumerable.Range(0, ReviewSchedule.MaximumStep + 1)
            .Select(step => ((long)ReviewSchedule.IntervalAt(step).TotalMilliseconds).ToString(CultureInfo.InvariantCulture)));
        var requiredStageAttempts = SkillEvidence.RequiredStageAttempts.ToString(CultureInfo.InvariantCulture);
        var requiredStageIndependent = SkillEvidence.RequiredStageIndependentCorrect.ToString(CultureInfo.InvariantCulture);
        var requiredRetentionConfirmations = SkillEvidence.RequiredRetentionConfirmations.ToString(CultureInfo.InvariantCulture);

        return $$$"""
skillAverage(p){const values=Object.values((p&&p.mastery)||{}).map(v=>Number(v)).filter(v=>Number.isFinite(v));return values.length?values.reduce((a,b)=>a+b,0)/values.length:0.05;}
  pickStage(stage,buckets,reviewRate=.25){const top=Math.max(1,Math.min(5,Number(stage)||1));let current=top-1;while(current>0&&!(buckets[current]&&buckets[current].length))current--;const active=(buckets[current]||[]).map(fn=>({fn:fn,difficulty:current+1})),previous=[];for(let i=0;i<current;i++)for(const fn of (buckets[i]||[]))previous.push({fn:fn,difficulty:i+1});const pool=previous.length&&Math.random()<reviewRate?previous:(active.length?active:previous);if(!pool.length)throw new Error('No questions configured for stage '+top);const picked=pool[this.rand(0,pool.length-1)],q=picked.fn();q.difficulty=picked.difficulty;return q;}
  curriculumData(){if(this._curriculumData)return this._curriculumData;const units={{{catalogJson}}},lanes={{{lanesJson}}},byId=new Map(),byTopic=new Map(),laneByUnit=new Map(),prerequisitesById=new Map();for(const unit of units){byId.set(unit.id,unit);if(!byTopic.has(unit.topicId))byTopic.set(unit.topicId,[]);byTopic.get(unit.topicId).push(unit);prerequisitesById.set(unit.id,unit.prerequisites||[]);}for(const lane of lanes)for(const id of lane)laneByUnit.set(id,lane);this._curriculumData={revision:{{{catalogRevisionJson}}},units:units,lanes:lanes,byId:byId,byTopic:byTopic,topicIds:[...byTopic.keys()],laneByUnit:laneByUnit,prerequisitesById:prerequisitesById,normalizedProfiles:new WeakSet(),topology:null};return this._curriculumData;}
  curriculumCatalog(){return this.curriculumData().units;}
  curriculumLaneIds(){return this.curriculumData().lanes;}
  curriculumUnit(k){return this.curriculumData().byId.get(k)||null;}
  curriculumUnitsForTopic(k){return this.curriculumData().byTopic.get(k)||[];}
  effectiveGrade(p){return Math.max(1,Math.min(9,Number(p&&p.grade)||1));}
  schoolGradeName(value){const grade=Math.max(1,Math.min(9,Number(value)||1));return grade<=6?'小学'+grade+'年':'中学'+(grade-6)+'年';}
  gradeLabel(p){return this.schoolGradeName(this.effectiveGrade(p))+'生';}
  learningStage(p){const level=this.skillLevel(p),stars=Number(p.stars)||0;if(stars<15&&level<=1)return 1;if(stars<45||level<=2)return 2;if(stars<90||level<=3)return 3;if(stars<150||level<=4)return 4;return 5;}
  blankUnitStat(){return{attempts:0,independent:0,assisted:0,revealed:0,errors:0,confidence:.05,reviewStep:0,retentionStep:0,lastAttemptAt:null,nextReviewAt:null,retentionStartedAt:null,masteredAt:null,level:1,stageAttempts:0,stageIndependent:0};}
  completedUnitStat(now=Date.now()){return{...this.blankUnitStat(),confidence:.99,retentionStep:{{{requiredRetentionConfirmations}}},retentionStartedAt:now,masteredAt:now,level:5};}
  normalizeUnitStat(old,mastery=.05){const base=this.blankUnitStat(),m=this.clamp(Number(mastery)||.05,.05,.99),mastered=Number(old&&old.masteredAt)||null,retentionStarted=Number(old&&old.retentionStartedAt)||(mastered?mastered:null),derived=retentionStarted?5:Math.max(1,Math.min(5,Math.floor(m*5)+1));return{...base,attempts:Number(old&&old.attempts)||0,independent:Number(old&&old.independent)||0,assisted:Number(old&&old.assisted)||0,revealed:Number(old&&old.revealed)||0,errors:Number(old&&old.errors)||0,confidence:this.clamp(Number(old&&old.confidence)||m,.05,.99),reviewStep:Math.max(0,Math.min(3,Number(old&&old.reviewStep)||0)),retentionStep:Math.max(0,Math.min({{{requiredRetentionConfirmations}}},Number(old&&old.retentionStep)||(mastered?{{{requiredRetentionConfirmations}}}:0))),lastAttemptAt:Number(old&&old.lastAttemptAt)||null,nextReviewAt:Number(old&&old.nextReviewAt)||null,retentionStartedAt:retentionStarted,masteredAt:mastered,level:Math.max(1,Math.min(5,Number(old&&old.level)||derived)),stageAttempts:Number(old&&old.stageAttempts)||0,stageIndependent:Number(old&&old.stageIndependent)||0};}
  ensureLearningProfile(p){if(!p||typeof p!=='object')return p;const data=this.curriculumData();if(data.normalizedProfiles.has(p))return p;const catalog=data.units,wasV5=Number(p.learningSchema)>=5,legacyGrade=this.effectiveGrade(p),oldTopicStats=p.skillStats&&typeof p.skillStats==='object'?p.skillStats:{},oldMastery=p.mastery&&typeof p.mastery==='object'?p.mastery:{};p.mastery=oldMastery;p.skillStats=oldTopicStats;p.cleared=p.cleared&&typeof p.cleared==='object'?p.cleared:{};p.unitStats=p.unitStats&&typeof p.unitStats==='object'?p.unitStats:{};if(wasV5){if(p.learningCatalogRevision===data.revision){data.normalizedProfiles.add(p);return p;}}if(!wasV5&&!p.legacyTopicStats)p.legacyTopicStats=JSON.parse(JSON.stringify(oldTopicStats));const migrated={...p.unitStats},legacyTargets=new Map();if(!wasV5)for(const [topic,units] of data.byTopic){const eligible=units.filter(candidate=>candidate.grade<=legacyGrade),target=eligible.find(candidate=>candidate.grade===legacyGrade)||eligible[eligible.length-1];legacyTargets.set(topic,target);}for(const unit of catalog){if(p.unitStats[unit.id]){migrated[unit.id]=this.normalizeUnitStat(p.unitStats[unit.id],p.mastery[unit.id]||p.mastery[unit.topicId]);continue;}if(wasV5){migrated[unit.id]=this.blankUnitStat();continue;}const old=oldTopicStats[unit.topicId]||{},evidence=(Number(old.attempts)||0)>0||Number(old.lastAttemptAt)>0,wasComplete=!!(p.cleared[unit.topicId]||old.masteredAt||old.retentionStartedAt),target=legacyTargets.get(unit.topicId),beforeTarget=target&&unit.order<target.order;if(wasComplete&&unit.grade<=legacyGrade)migrated[unit.id]=this.completedUnitStat(Number(old.masteredAt)||Number(old.lastAttemptAt)||Date.now());else if(evidence&&beforeTarget)migrated[unit.id]=this.completedUnitStat(Number(old.lastAttemptAt)||Date.now());else if(evidence&&target&&unit.id===target.id)migrated[unit.id]=this.normalizeUnitStat(old,oldMastery[unit.topicId]);else migrated[unit.id]=this.blankUnitStat();}p.unitStats=migrated;for(const unit of catalog)p.mastery[unit.id]=migrated[unit.id].confidence;p.learningSchema=5;p.learningCatalogRevision=data.revision;data.normalizedProfiles.add(p);return p;}
  migrateProfiles(profiles){return (Array.isArray(profiles)?profiles:[]).map(p=>this.ensureLearningProfile({...p,mastery:{...(p.mastery||{})},skillStats:{...(p.skillStats||{})},unitStats:{...(p.unitStats||{})},cleared:{...(p.cleared||{})}}));}
  resolveUnitId(p,k){this.ensureLearningProfile(p);if(this.curriculumUnit(k))return k;const active=this.curriculumUnit(p&&p._activeUnitId);if(active&&active.topicId===k)return active.id;const units=this.curriculumUnitsForTopic(k),configured=this.state&&this.state.settings&&this.state.settings.topics,enabled=units.filter(unit=>!configured||configured[unit.topicId]!==false),unlocked=new Set(this.unlockedGradeTopics(p)),scoped=enabled.filter(unit=>unlocked.has(unit.id)),pool=scoped.length?scoped:(enabled.length?enabled:units);if(!pool.length)return k;return (pool.find(unit=>{const s=p.unitStats[unit.id];return !(s&&(s.retentionStartedAt||s.masteredAt));})||pool[pool.length-1]).id;}
  topicStat(p,k){const id=this.resolveUnitId(p,k);if(p&&p._stageUnitId===id&&p._stageUnitStat)return p._stageUnitStat;return p.unitStats[id]||(p.unitStats[id]=this.blankUnitStat());}
  statStage(s){const saved=Number(s&&s.level);if(Number.isFinite(saved))return Math.max(1,Math.min(5,saved));return Math.max(1,Math.min(5,Math.floor((Number(s&&s.confidence)||.05)*5)+1));}
  topicStage(p,k){return this.statStage(this.topicStat(p,k));}
  topicLearningStage(p,k){return this.topicStat(p,k).retentionStartedAt?6:this.topicStage(p,k);}
  reviewStage(p,k){const s=this.topicStat(p,k),stage=this.statStage(s),due=!!s.nextReviewAt&&s.nextReviewAt<=Date.now();if(s.retentionStartedAt)return 5;return due&&stage>1?Math.max(1,stage-1):stage;}
  profileAtStage(p,k,stage){const base=this.ensureLearningProfile(p),id=this.resolveUnitId(base,k),level=Math.max(1,Math.min(5,stage)),levels=[.05,.25,.45,.65,.85],unit=this.curriculumUnit(id),source=Object.create(base);source._activeUnitId=id;source._stageUnitId=id;source._stageUnitStat=Object.freeze({...base.unitStats[id],level:level,confidence:levels[level-1]});if(unit)source.grade=unit.grade;this.curriculumData().normalizedProfiles.add(source);return source;}
  topicMastered(p,k){return !!this.topicStat(p,k).masteredAt;}
  topicComplete(p,k){const s=this.topicStat(p,k);return !!(s.retentionStartedAt||s.masteredAt);}
  topicDue(p,k,now=Date.now()){const n=this.topicStat(p,k).nextReviewAt;return !!n&&n<=now;}
  topicReady(p,k,now=Date.now()){const s=this.topicStat(p,k),due=!!s.nextReviewAt&&s.nextReviewAt<=now;return !!s.masteredAt&&s.retentionStep>={{{requiredRetentionConfirmations}}}&&!due;}
  stageEvidenceRequired(level){return level<=2?{attempts:4,independent:3}:level<=4?{attempts:5,independent:4}:{attempts:{{{requiredStageAttempts}}},independent:{{{requiredStageIndependent}}}};}
  stageEvidenceReady(s){const req=this.stageEvidenceRequired(s.level),accuracy=s.stageAttempts?s.stageIndependent/s.stageAttempts:0;return s.stageAttempts>=req.attempts&&s.stageIndependent>=req.independent&&accuracy>=req.independent/req.attempts;}
  beginRetention(s,now,intervals){s.retentionStartedAt=now;s.retentionStep=0;s.reviewStep=0;s.stageAttempts=0;s.stageIndependent=0;s.nextReviewAt=now+intervals[0];}
  markCleared(p,k,now=Date.now()){const id=this.resolveUnitId(p,k),s=p.unitStats[id]||(p.unitStats[id]=this.blankUnitStat());if(s.retentionStep>={{{requiredRetentionConfirmations}}}&&!s.masteredAt){s.masteredAt=now;(p.cleared=p.cleared||{})[id]=true;}}
  recordEvidence(p,q,outcome,points){this.ensureLearningProfile(p);const id=q.unitId||this.resolveUnitId(p,q.topic),unit=this.curriculumUnit(id),s=p.unitStats[id]||(p.unitStats[id]=this.blankUnitStat()),now=Date.now(),intervals=[{{{reviewIntervals}}}],difficulty=Math.max(1,Math.min(5,Number(q.difficulty)||s.level)),aligned=!s.retentionStartedAt&&difficulty===s.level,wasDue=!!s.nextReviewAt&&s.nextReviewAt<=now,retentionReview=!!s.retentionStartedAt&&wasDue&&q.sessionRole==='review'&&difficulty===5;s.attempts++;s.lastAttemptAt=now;if(aligned)s.stageAttempts++;if(outcome==='independent'){s.independent++;if(aligned)s.stageIndependent++;s.confidence=this.clamp(s.confidence+.12,.05,.99);}else if(outcome==='assisted'){s.assisted++;s.confidence=this.clamp(s.confidence-.03,.05,.99);}else if(outcome==='revealed'){s.revealed++;s.errors++;s.confidence=this.clamp(s.confidence-.08,.05,.99);}else{s.errors++;s.confidence=this.clamp(s.confidence-.10,.05,.99);}if(s.retentionStartedAt){if(retentionReview){if(outcome==='independent'){s.retentionStep=Math.min({{{requiredRetentionConfirmations}}},s.retentionStep+1);s.reviewStep=s.retentionStep;s.nextReviewAt=now+intervals[Math.max(0,Math.min(3,s.retentionStep))];this.markCleared(p,id,now);}else{s.retentionStep=0;s.reviewStep=0;s.nextReviewAt=now+intervals[0];}}else if(difficulty===5&&outcome!=='independent'){s.retentionStep=0;s.reviewStep=0;s.nextReviewAt=now+intervals[0];}}else{if(outcome==='independent'){if(!s.nextReviewAt||s.nextReviewAt<=now){s.nextReviewAt=now+intervals[Math.max(0,Math.min(3,s.reviewStep))];s.reviewStep=Math.min(3,s.reviewStep+1);}}else{s.nextReviewAt=now;s.reviewStep=0;}if(aligned&&this.stageEvidenceReady(s)){if(s.level<5){s.level++;s.stageAttempts=0;s.stageIndependent=0;}else this.beginRetention(s,now,intervals);}}p.mastery[id]=s.confidence;if(unit){p.mastery[unit.topicId]=s.confidence;p.skillStats[unit.topicId]=s;}const sess=this.state.session;if(sess){const fallback=outcome==='independent'?1:0,awarded=this.clamp(Number.isFinite(Number(points))?Number(points):fallback,0,1);sess.correct=(Number(sess.correct)||0)+awarded;if(q.sessionRole==='target'||q.sessionRole==='exit'){sess.targetAsked++;if(outcome==='independent')sess.targetIndependent++;}if(outcome==='independent')delete sess.supportTopics[id];else sess.supportTopics[id]=true;}return outcome;}
  hissanComplete(p){return this.curriculumUnitsForTopic('hissan').some(unit=>this.topicComplete(p,unit.id));}
  curriculumTopology(p){const data=this.curriculumData(),cfg=this.state&&this.state.settings,configured=cfg&&cfg.topics,prefer=!!(cfg&&cfg.preferSchoolGrade),minimumGrade=this.effectiveGrade(p),signature=data.topicIds.map(topic=>!configured||configured[topic]!==false?'1':'0').join(''),key=(prefer?'1':'0')+'|'+minimumGrade+'|'+signature;if(data.topology&&data.topology.key===key)return data.topology;const lanes=this.curriculumLaneIds().map(lane=>{const enabled=lane.filter(id=>{const unit=data.byId.get(id);return unit&&(!configured||configured[unit.topicId]!==false);});return prefer?enabled.filter(id=>data.byId.get(id).grade>=minimumGrade):enabled;}).filter(lane=>lane.length),unitIds=[],availableUnitIds=new Set(),laneByUnit=new Map(),unitIdsByGrade=new Map();for(const lane of lanes)for(const id of lane){const unit=data.byId.get(id);unitIds.push(id);availableUnitIds.add(id);laneByUnit.set(id,lane);if(!unitIdsByGrade.has(unit.grade))unitIdsByGrade.set(unit.grade,[]);unitIdsByGrade.get(unit.grade).push(id);}data.topology={key:key,lanes:lanes,unitIds:unitIds,availableUnitIds:availableUnitIds,laneByUnit:laneByUnit,unitIdsByGrade:unitIdsByGrade};return data.topology;}
  curriculumLanes(p){return this.curriculumTopology(p).lanes;}
  progressionMemo(p,key,build){const scope=this._progressionScope;if(!scope||scope.profile!==p)return build();if(scope.values.has(key))return scope.values.get(key);const value=build();scope.values.set(key,value);return value;}
  activeCurriculumGrade(p){return this.progressionMemo(p,'activeCurriculumGrade',()=>{const byGrade=this.curriculumTopology(p).unitIdsByGrade,grades=[...byGrade.keys()].sort((a,b)=>a-b);if(!grades.length)return this.effectiveGrade(p);for(const grade of grades)if(byGrade.get(grade).some(id=>!this.topicComplete(p,id)))return grade;return grades[grades.length-1];});}
  unlockedGradeTopics(p){return this.progressionMemo(p,'unlockedGradeTopics',()=>{const activeGrade=this.activeCurriculumGrade(p),out=[];for(const [grade,ids] of this.curriculumTopology(p).unitIdsByGrade)if(grade<=activeGrade)out.push(...ids);return out;});}
  currentGradeTopics(p){return this.progressionMemo(p,'currentGradeTopics',()=>this.curriculumTopology(p).unitIdsByGrade.get(this.activeCurriculumGrade(p))||[]);}
  gradeTopics(p){return this.unlockedGradeTopics(p);}
  directPrerequisites(p,k){const data=this.curriculumData(),unit=this.curriculumUnit(this.resolveUnitId(p,k)),available=this.curriculumTopology(p).availableUnitIds,prerequisites=unit?(data.prerequisitesById.get(unit.id)||(unit.prerequisites||[])):[];return prerequisites.filter(req=>available.has(req));}
  topicNeedsSupport(p,k){const s=this.topicStat(p,k);return s.attempts>0&&(Number(s.confidence)<.5||this.topicDue(p,k));}
  remediationTopics(p,k){const id=this.resolveUnitId(p,k);return this.progressionMemo(p,'remediation:'+id,()=>{if(!this.topicNeedsSupport(p,id))return[];const out=[],emitted=new Set(),visiting=new Set(),walk=(topic,isRoot)=>{if(visiting.has(topic))return false;visiting.add(topic);const pending=this.directPrerequisites(p,topic).filter(req=>!this.topicReady(p,req));let found=false;for(const req of pending)found=walk(req,false)||found;visiting.delete(topic);if(!isRoot&&!found){if(!emitted.has(topic)){emitted.add(topic);out.push(topic);}return true;}return found;};walk(id,true);return out;});}
  introducedTopics(p){return this.progressionMemo(p,'introducedTopics',()=>{const unlocked=this.unlockedGradeTopics(p),unlockedSet=new Set(unlocked),out=[],seen=new Set(),append=id=>{if(!unlockedSet.has(id)||seen.has(id))return;seen.add(id);out.push(id);};for(const lane of this.curriculumLanes(p)){let frontier=lane.findIndex(id=>unlockedSet.has(id)&&!this.topicComplete(p,id));if(frontier<0)frontier=lane.length-1;for(let i=0;i<=frontier;i++)append(lane[i]);}for(const id of unlocked){const s=this.topicStat(p,id);if(s.attempts>0||s.masteredAt)append(id);}return out;});}
  allowedTopics(p){return this.progressionMemo(p,'allowedTopics',()=>{const introduced=this.introducedTopics(p),base=introduced.length?introduced:this.unlockedGradeTopics(p),out=[],seen=new Set(),append=id=>{if(seen.has(id))return;seen.add(id);out.push(id);};for(const id of base)append(id);for(const id of base)for(const req of this.remediationTopics(p,id))append(req);return out;});}
  frontierTopics(p){return this.progressionMemo(p,'frontierTopics',()=>{const unlocked=new Set(this.unlockedGradeTopics(p)),out=[],outSeen=new Set();for(const lane of this.curriculumLanes(p)){const next=lane.find(id=>unlocked.has(id)&&!this.topicComplete(p,id));if(next&&!outSeen.has(next)){outSeen.add(next);out.push(next);}}const allowed=this.allowedTopics(p),candidates=out.slice(),candidateSeen=new Set(candidates);for(const id of allowed)if(!this.topicComplete(p,id)&&this.topicNeedsSupport(p,id)&&!candidateSeen.has(id)){candidateSeen.add(id);candidates.push(id);}const remedial=[],remedialSeen=new Set();for(const id of candidates)for(const req of this.remediationTopics(p,id))if(!remedialSeen.has(req)){remedialSeen.add(req);remedial.push(req);}return remedial.length?remedial:(out.length?out:allowed);});}
  laneProgress(p,k){const id=this.resolveUnitId(p,k);return this.progressionMemo(p,'laneProgress:'+id,()=>{const activeGrade=this.activeCurriculumGrade(p),lane=(this.curriculumTopology(p).laneByUnit.get(id)||[id]).filter(item=>this.curriculumUnit(item).grade===activeGrade),done=lane.filter(item=>this.topicComplete(p,item)).length;return done/Math.max(1,lane.length);});}
  nextCurriculumTopic(p){return this.progressionMemo(p,'nextCurriculumTopic',()=>{const front=this.frontierTopics(p);if(!front.length)return this.weakestTopic(p,this.allowedTopics(p));let best=front[0],bestProgress=this.laneProgress(p,best);for(let i=1;i<front.length;i++){const candidate=front[i],progress=this.laneProgress(p,candidate);if(progress<bestProgress){best=candidate;bestProgress=progress;}}return best;});}
  dueTopics(p,now=Date.now()){return this.progressionMemo(p,'dueTopics:'+now,()=>this.allowedTopics(p).filter(id=>this.topicDue(p,id,now)));}
  weightedPick(p,pool){const source=pool&&pool.length?pool:this.allowedTopics(p),preferred=[],seen=new Set();for(const id of source){const remedial=this.remediationTopics(p,id),candidates=remedial.length?remedial:[id];for(const candidate of candidates)if(!seen.has(candidate)){seen.add(candidate);preferred.push(candidate);}}const ids=preferred.length?preferred:source;if(!ids.length)throw new Error('No enabled curriculum units');const weights=ids.map(id=>.25+(1-this.topicStat(p,id).confidence)*1.75+(this.topicDue(p,id)?1:0));let sum=weights.reduce((a,b)=>a+b,0),r=Math.random()*sum;for(let i=0;i<ids.length;i++){r-=weights[i];if(r<=0)return ids[i];}return ids[0];}
  weakestTopic(p,pool){const ids=pool&&pool.length?pool:this.allowedTopics(p);if(!ids.length)return undefined;let best=ids[0],bestStat=this.topicStat(p,best);for(let i=1;i<ids.length;i++){const candidate=ids[i],stat=this.topicStat(p,candidate),confidenceDelta=stat.confidence-bestStat.confidence,independentDelta=stat.independent-bestStat.independent;if(confidenceDelta<0||(confidenceDelta===0&&independentDelta<0)){best=candidate;bestStat=stat;}}return best;}
  progressionView(p){const previous=this._progressionScope,scope={profile:p,values:new Map()};this._progressionScope=scope;let view;try{const activeGrade=this.activeCurriculumGrade(p),gradeTopics=this.gradeTopics(p),allowedTopics=this.allowedTopics(p),frontierTopics=this.frontierTopics(p),nextTopic=this.nextCurriculumTopic(p),availableTopicIds=new Set(),introducedTopicIds=new Set(),weakTopicIds=new Set();for(const id of gradeTopics){const unit=this.curriculumUnit(id);if(unit)availableTopicIds.add(unit.topicId);}for(const id of allowedTopics){const unit=this.curriculumUnit(id);if(!unit)continue;introducedTopicIds.add(unit.topicId);if((Number(p.mastery[id])||.05)<.5)weakTopicIds.add(unit.topicId);}view={activeGrade:activeGrade,gradeTopics:gradeTopics,allowedTopics:allowedTopics,frontierTopics:frontierTopics,nextTopic:nextTopic,availableTopicIds:availableTopicIds,introducedTopicIds:introducedTopicIds,weakTopicIds:weakTopicIds};}finally{this._progressionScope=previous;}return view;}
""";
    }
}
